### ISSUE TITLE
Is this project being actively developed?

### ISSUE THREAD

**Issue by coleifer** [ghaering/pysqlite#114]
Are you accepting feature requests or is this in maintenance mode? If you're planning to continue development, do you have a roadmap?

**Comment by ghaering** [comment]
Good question. It is definitely not actively developed. I was looking for a new mainteiner some time ago (two years or so), but nobody was interested.

**Comment by josephernest** [comment]
@ghaering 

Just to be sure: is `pysqlite` the module we have when doing `import sqlite3`, or another one?

If so, it's now part of the Python standard library (installed by default), isn't it?

Isn't it maintained by the core Python developers?

**Comment by josephernest** [comment]
Thanks @berkerpeksag for your answer.

I think it could be super useful to add more details in the README, because it's very easy to confuse between these different versions.

Suggested README @ghaering : 

____________________________

pysqlite
=====

pysqlite is a Python DB-API module for SQLite 3.

It is available for Python 2.x.

Online documentation can be found [here](https://pysqlite.readthedocs.org/en/latest/sqlite3.html).

You can get help from the community on the Google Group [python-sqlite](https://groups.google.com/forum/#!forum/).

Note: Python's standard-library built-in [`sqlite3` module](https://github.com/python/cpython/tree/master/Modules/_sqlite) is based on `pysqlite` (this project). However, they are maintained separately and they have slightly different APIs.

Maintainer: [Gerhard Häring](https://github.com/ghaering)
Maintainer of Python's standard-library `sqlite3` module: [Berker Peksag](https://github.com/berkerpeksag)


____

PS1: I think all these informations here ^^ are needed to not confuse the different versions.

PS2: the README could add a mention about:

    pip install pysqlite        # does this install *this* project or update Python's stdlib sqlite3?

**Comment by josephernest** [comment]
https://github.com/ghaering/pysqlite/pull/124

**Comment by josephernest** [comment]
@berkerpeksag If you're the Python core developer of sqlite3, maybe you're one of the few people who could have a (very quick) idea for https://github.com/ghaering/pysqlite/issues/123. I'm stuck on this since days...

**Comment by ghaering** [comment]
The question about maintenance mode was answered, closing this issue then.
