### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by nettrino** [ghaering/pysqlite#119]
When trying to execute an insert statement using `VALUES (?, ?)` and a large integer, I get an overflow error, whereas if I simply pass the whole statement as a string this works. 

Example:

`execute("INSERT OR IGNORE INTO TestTable(Number) VALUES (?)", (18446708610539800576))` fails, 
whereas
`execute("INSERT OR IGNORE INTO TestTable(Number) VALUES (18446708610539800576)")` succeeds

Windows 10
Python 3.6.3
sqlite 3.20.1

**Comment by nettrino** [comment]
I am sorry but I don't seem to understand. Shouldn't the pysqlite wrapper be consistent with SQLite? Why should the one fail and the other succeed on the exact same table? (the "Number" field is declared as UNSIGNED BIG INT btw)

**Comment by rogerbinns** [comment]
The first form uses a binding. pysqlite calls [sqlite3_prepare](https://sqlite.org/c3ref/prepare.html) with the statement text, then it goes to call [sqlite3_bind_int64](https://sqlite.org/c3ref/bind_blob.html) and discovers the value is too large to fit in int64 and raises the Python exception.

In the second form, only sqlite3_prepare is called.  SQLite accepts the text and does not raise an error on execution.  There is no [SQLite error code](https://sqlite.org/rescode.html#error) for an integer that is too big.  SQLite decided to silently promote overflowing integers into floating point.  Other situations it could occur would be adding or multiplying integers that then overflow.  This behaviour in SQLite3 will never be changed (would break the many billions of instances of SQLite in use.)

In theory pysqlite could be changed so that if the integer is too large for sqlite3_bind_in64 that it calls [sqlite3_bind_double](https://sqlite.org/c3ref/bind_blob.html) instead after converting the value to floating point.  However this will lose some precision (up to 11 bits).  So you get an exception and as a developer it is up to you what to do.

>  the "Number" field is declared as UNSIGNED BIG INT btw

You can declare it as anything you want (literally), but that won't change SQLite's behaviour.  It only supports up to 64 bit signed integers.  You can read more about [SQLite datatypes](https://sqlite.org/datatype3.html).

**Comment by nettrino** [comment]
Thanks for the clarification. I am aware about the SQLite datatype issue. I will go ahead and close this, but my take on it is that it is favorable to be consistent with what sqlite3 does rather than start introducing deviations.
