### ISSUE TITLE
How to update the sqlite3 module?

### ISSUE THREAD

**Issue by josephernest** [ghaering/pysqlite#123]
I'm using Python 2.7.6 on my Debian. I [compiled a Sqlite extension](https://stackoverflow.com/a/49815419/1422096) `spellfix`, I get this error when loading it: `sqlite3.OperationalError: ./spellfix.so: undefined symbol: sqlite3_malloc64`.

I think it might be because the `sqlite3` module is too old:

    import sqlite3
    print sqlite3.version          # 2.6.0
    print sqlite3.sqlite_version   # 3.8.2

(On another machine where `sqlite3.sqlite_version` is 3.8.7.x the extension loads fine).

I tried:

    pip install --upgrade pysqlite

but it's still the same: `sqlite3.sqlite_version` stays 3.8.2.

**How to upgrade the Python sqlite3 module?**

**Comment by berkerpeksag** [comment]
`pip install --upgrade pysqlite` will only upgrade the pysqlite module, not the underlying SQLite library. In order to upgrade SQLite, you either need to use the system package manager (`apt-get update sqlite3` for example) or build your own pysqlite with a newer SQLite. You can use the snippet posted by Gerhard at https://github.com/ghaering/pysqlite/issues/95#issuecomment-192242902 to do the latter (note that you may need to add `ext.include_dirs.append(".")` before line 152 in https://github.com/ghaering/pysqlite/blob/e728ffbcaeb7bfae1d6b7165369bd0ae16cabf95/setup.py#L152)

**Comment by josephernest** [comment]
Linked to this: https://stackoverflow.com/questions/49820873/upgrade-pythons-sqlite3-on-debian.

**Comment by josephernest** [comment]
@berkerpeksag Does `apt-get update sqlite3` update:

* the `sqlite` shared library present on the Debian, 
* or the python `sqlite3` built-in module
* or anything else?
