### ISSUE TITLE
DateTime should be represented without microseconds

### ISSUE THREAD

**Issue by ADR-007** [ghaering/pysqlite#127]
Hello! I am glad to use this driver, but I found one bug: datetime is representing with microseconds.

But when you generate request like that:
```
SELECT time FROM some_table
WHERE time < '2000-10-10 10:00:00.000000';
```
You will see time == '2000-10-10 10:00:00' in the results. It happens because  '2000-10-10 10:00:00'  <  '2000-10-10 10:00:00.000000'  (looks like SQLite compare datetime as strings). As I understand this driver responsive for it.

(I saw this with SQLAlchemy)

**Comment by ghaering** [comment]
If you use the query like you wrote in your comment, pysqlite has nothing to do with it. Only if you ever used datetime.datetime and inserted it using pysqlite. The problem is that SQLite3 does not have any concept of a TIMESTAMP type, so we try to work around it using strings. Which works fine if the (de)serialisation in consistent.

To be on the safe side, you could go the ugly way and store timestamps as numbers.
