### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by kgnk** [ghaering/pysqlite#89]
I installed "Microsoft Visual C++ Compiler Package for Python 2.7" which has a different directory structure than VS2008. I could work around that issue, but the setup.py is totally reliant on pkg-config, which does not exist on Windows.

**Comment by ghaering** [comment]
I thought that https://github.com/ghaering/pysqlite/commit/18960b8449fdbffecc972f5879b05a76de83f64d has fixed the dependency on pkg-config.

Shouldn't distutils pick up your Microsoft Compiler and just work, provided that the SQLite files from the amalgamation are found?

**Comment by kgnk** [comment]
For the compiler command, I get include options like `-Iis -Inot -Irecognizeed -Ias -Ian -Iinternal -Ior -Iexternal -Icommand -Ioperable -Iprogram -Ior -Ibatch -Ifile`.

I'm sure the call to pkg-config returns this string. I can help out by checking fixes, but I'm new to Python, so I won't be much help in contributing code.

I was able to bypass this issue by downloading a wheel from [http://www.lfd.uci.edu/~gohlke/pythonlibs/]

**Comment by mobiusklein** [comment]
Depending upon how MSVC is installed, distutils may not pick it up automatically. I had to replace `distutils` with `setuptools` in setup.py in order to make it find `vcvars.bat`.

I also saw this same `-I<cmd.bat failure>` message @kgnk mentioned. This is because `commands.getstatusoutput` didn't raise `OSError` when `cmd.bat` failed to execute `pkg-config`. If `MyBuilder._pkgconfig` raised `OSError` when the status returned by `commands.getstatusoutput`, then the compiler doesn't know where to look for the sqlite3 header files.

**Comment by mobiusklein** [comment]
I cloned this repository, and download the source amalgamation from SQlite's website. 

After downloading the amalgamation for SQLite 3.9.2, I extracted `sqlite3.h`, `sqlite3.c`, and `sqlite3ext.h` into the repository root directory, adjacent to setup.py. 

I adjusted the setup script to use setuptools, replacing `build` with `build_py`, and set `MyBuildExt._pkgconfig` to raise `OSError` when the status returned by `getstatusoutput` was 1. I also set `include_dirs = ["."]` to ensure that the compiler found the source files for sqlite.

Attempting to build first triggered a compiler error in [src/cursor.c:618](https://github.com/ghaering/pysqlite/blob/master/src/cursor.c#L618)  where `lastrowid` was declared in the middle of the function. Moving the declaration to the top of the function satisfied the compiler.

Building proceeded until the end where it failed "unable to open sqlite3.lib". I downloaded the precompiled Windows binary from SQLite's website, which contained the DLL and paired sqlite3.def file. I used the `lib` utility bundled with MSVC 2008 to produce `sqlite3.lib` from `sqlite3.def` for my machine architecture as described by [this blog](https://raginginverno.wordpress.com/2013/01/23/welcome/).

```bat
% From MSVC command prompt
lib /def:sqlite3.def /out:sqlite3.lib /MACHINE:x64
```

Building proceeded past the previous point of failure, however once installed, attempting to import the `dbapi2` module caused a DLL load error. To resolve this, I forced `MyBuildExt.amalgamation = True`, which included static compilation of `sqlite3.c` in the generated `pyd`, which resolved the issue.

Following this, I was able to successfully load the the dbapi2 submodule and create a connection, execute a `CREATE VIRTUAL TABLE` statement using `fts4`.

Is there a more complete test I should use?

**Comment by Vultaire** [comment]
I'm quite interested if there's a way to get this up and running on Windows.  People I've been working with have hit problems in some cases with the old version of SQLite packaged with Windows Python, and while we're experimenting with running updated builds of the SQLite DLL, I'd also like for us to test with a more recent Python binding than that provided in Python 2.7.x.

I don't quite fully grok the procedure mobiusklein is using to build; a diff of the setup.py would be quite useful.  I can probably try an experiment when I have more time and try to reproduce this...

I did alternatively try the procedure at http://trac.edgewall.org/wiki/PySqlite.  That seemed to get me most of the way there, but I hit some errors for some reason; haven't dug deep enough to figure out why yet.  I am using the vcvarsall.bat from the VC++ for Python 2.7 bundle, but regardless, no luck yet.

Anyway, I will likely experiment more myself, but of course it'd be great if someone who's had more luck can provide more details and perhaps fill in this gap.

**Comment by mobiusklein** [comment]
I've cleaned up the build process, and hosted a working copy at https://github.com/mobiusklein/pysqlite. I've included SQLite 3.92 sources in the repository, including the compressed Windows compilation artefacts I needed to solve the linking problem. I'm also using the VC++ Python 2.7 bundle, and `setuptools` should find it automatically.

**Comment by Vultaire** [comment]
mobiusklein: Thanks for the quick feedback!  I'll definitely try it out when time permits.

**Comment by Vultaire** [comment]
Regarding the upstream setup.py: something simple like this, albeit slightly ugly, should unblock building at a basic level:

            if os.name == "nt":
                ext.include_dirs = ["."]
                ext.library_dirs = ["."]
            else:
                try:
                    ext.include_dirs = self._pkgconfig_include_dirs("sqlite3")
                    ext.library_dirs = self._pkgconfig_library_dirs("sqlite3")
                except OSError:
                    pass # no pkg_config installed

This makes it so on Windows the expectation is that any sqlite sources, headers, and/or libs necessary to build should be dumped into the root of the pysqlite2 package prior to doing a build.

**Comment by Vultaire** [comment]
While the setup.py (using distutils) won't auto-detect the VC++ for Python 2.7 bundle, it can be used manually if you do the following:

* Run the vcvarsall.bat by hand.
* Set the environment variable DISTUTILS_USE_SDK to a non-empty value, e.g. 1.
* Set the environment variable MSSdk to a non-empty value, e.g. 1.

This will effectively turn off distutils's auto-search for VC++ 9.0 and rely on your current environment instead.

**Comment by Vultaire** [comment]
Finally, while I'm now able to build with the upstream sources, the dbapi2 module has problems being imported unless I statically link SQLite.  I haven't figured out why this is yet.  This isn't ideal, but it is likely good enough for my purposes.

**Comment by Vultaire** [comment]
So, here's the solution as far as I can tell:

* Copy the sqlite amalgation sources, along with sqlite3.dll and sqlite3.lib, into the pysqlite2 root directory.
* Do the os-specific tweak mentioned 3 comments prior.
* Install via "python setup.py install".  (Either via auto-detected VC9.0, or via the VC++ for Python 2.7 bundle using the procedure 2 comments prior.)
* Copy sqlite3.dll into the installed pysqlite2 package's directory.  (Or tweak setup.py to do this for you.)

Yes, that's basically it.  The generated .pyd file should be valid and usable.

Now, the final gotcha is regarding sqlite3.dll.  I haven't quite grokked this bit yet.  The generated .pyd file actually _should_ link to sqlite3.dll; however, it doesn't work with the sqlite3.dll in the &lt;pythondir>\DLLs directory, even if you replace the DLL there with a new version.  I don't know why, nor do I know how Python gets other libraries to use the DLLs in the DLLs directory.  *But,* if you copy the version of sqlite3.dll _into_ the pysqlite2 package, then it'll start working.  So it is definitely possible to do dynamic linking to sqlite3.dll, and this may actually be preferable since you can keep a separate copy of the DLL than that used by Python itself.

Just to demonstrate:

    C:\Users\pdgoins>python -c "import sqlite3; print (sqlite3.version, sqlite3.sqlite_version)"
    ('2.6.0', '3.6.21')
    
    C:\Users\pdgoins>python -c "from pysqlite2 import dbapi2 as sqlite3; print (sqlite3.version, sqlite3.sqlite_version)"
    ('2.8.1', '3.10.2')

...I just wish I knew _why_ pysqlite2 doesn't pick up the DLL in &lt;pythondir>\DLLs...  But that may not be so important here.

**Comment by Vultaire** [comment]
Also note: the reference to _PyInt_AsInt in connection.c basically makes the current version of the module only compatible on Python 2.7.4+.  ...Not a problem for me, but I did hit this initially since I was running Python 2.7.3 (for reasons I won't go into).

**Comment by mobiusklein** [comment]
The reason you're encountering the DLL location problem has to do with the way the Extension module is configured to be built. If you look in `setup.py`, circa line 205:

```python
            ext_modules = [Extension( name="pysqlite2._sqlite",
                                      sources=sources,
                                      include_dirs=include_dirs,
                                      library_dirs=library_dirs,
                                      runtime_library_dirs=runtime_library_dirs,
                                      libraries=libraries,
                                      extra_objects=extra_objects,
                                      define_macros=define_macros
                                      )],
```

The Extension object that defines how to compile and link the C Extension is told where to find things during link time and runtime which are global variables defined at the top of the file. Windows doesn't have a convenient lookup path for DLLs, like *nix's DL_LIBRARY_PATH environment variable, so it instead probes each directory along your path until it finds a DLL that matches the name you're asking for. I expect that if you change one of these, you'll be able to control where the C extension expects to load the sqlite3.dll  file.

That said, think about the environment you deploy your software in. Do you have total control where you should have permission to put DLLs wherever you like, and where said DLLs will be shared between multiple programs, or is it isolated to the one program which will be tailored towards that specific version of the library you're linking with?

I apparently failed to mention I was using the amalgam build because for my purposes I do not want to change more about the end-user environment than I have to. I can ensure I have access to certain features by using static linkage without worrying about anything else that the user has set up.

**Comment by Vultaire** [comment]
Thanks for the comment.  I may dig a little deeper on the runtime_library_dirs parameter.

However, again, this is primarily for my curiosity, it's not that important.

And to be clear: my intent was simply to be able to use the DLLs already installed in the user's Python environment if present, but with the pysqlite2's package directory taking precedence.  This would allow users to in theory merely update the shim if they want rather than being forced to upgrade both the shim *and* the DLL.  Although really, in most cases both pieces are likely going to be desired, so the current solution (sqlite3.dll deployed inside the pysqlite2 package) is fine.

Totally in agreement with you about avoiding unnecessary changes to the user's environment.  I have the same goal here.

**Comment by micahcochran** [comment]
I had the same problem with Windows installation.  The modification made by the @mobiusklein worked for installation and testing on my box.  Thanks.  I want to keep abreast of future updates on this matter.

**Comment by ghaering** [comment]
For Windows, please switch to the sqlite3 module in the standard library, this is maintained much better than this original one. It also works on Python 3.x, which is the future.
