### ISSUE TITLE
Publish binary wheels for Windows on PyPI

### ISSUE THREAD

**Issue by rutsky** [ghaering/pysqlite#94]
It's painful to build software on Windows.

As an option _where_ to build wheels [AppVeyor CI](https://www.appveyor.com/docs) can be used: AFAIK it can be configured to build and even publish on PyPI binary packages.

**Comment by ctoth** [comment]
I agree that Windows wheel  support would be a huge win!
There's also the new manylinux wheel platform defined in PEP 513, so universal wheel installation is now possible. That said, Windows is definitely the painpoint at present and wheels would be welcomed even if manually uploaded :)

**Comment by Vultaire** [comment]
+1 with regards to using AppVeyor to build wheels.

Building pysqlite on Windows *via* Windows isn't quite simple, but there are comments on #89 which document some tweaks to the setup.py which make this possible.  (There is a script for cross-compiling which looks old, but may be what the author uses.)

Additionally, there's the question of whether to statically or dynamically bind to SQLite.  I prefer dynamic since that would allow the DLL to be swapped out by the user if so desired.  The only downside I know of with this approach is that I don't know how to set up the build to use the sqlite3.dll located in <python_dir>\DLLs; I can only get it to work if I put a copy of sqlite3.dll in the pysqlite2 package's directory alongside _sqlite.pyd.  While not critical, this is annoying and somewhat confusing.

(To be perfectly clear: I've messed with this quite a bit, but I am not a dev on this project.)

**Comment by Vultaire** [comment]
Also, just as knowledge sharing, there are unofficial wheels here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pysqlite

...I'd much rather have official wheels, though.

**Comment by ghaering** [comment]
This project is feature complete and in maintenance-only mode, nothing new will be implemented here. Closing.
